In [2]:
print("Hello, Summer!")

Hello, Summer!


In [3]:
import numpy as np

a = np.random.randint(0, 10, size=10)
print(a)
b = np.random.randint(0, 10, size=10)
print(b)
c = np.random.randint(0, 10, size=10)
print(c)

a = a[c > 5.0]
b = b[c > 5.0]
c = c[c > 5.0]

print("after\n",a)
print(b)
print(c)

[4 6 7 5 4 7 4 9 5 6]
[8 8 7 4 5 9 0 1 5 4]
[7 4 8 8 8 5 3 0 6 1]
after
 [4 7 5 4 5]
[8 7 4 5 5]
[7 8 8 8 6]
